"""empty message

Revision ID: 2752da143dd1
Revises: 
Create Date: 2021-03-29 22:43:15.170602

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2752da143dd1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('actors', 'age',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('actors', 'gender',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('actors', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('movies', 'release_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('movies', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('movies', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('movies', 'release_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('actors', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('actors', 'gender',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('actors', 'age',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
